# Generated by Django 2.1.5 on 2019-01-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrucksData',
            fields=[
                ('truck_number', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('insurance_number', models.PositiveIntegerField()),
                ('insurance_expiry', models.DateField()),
                ('fitness_certificate_id', models.CharField(blank=True, max_length=30, null=True)),
                ('fitness_certificate_expiry', models.DateField(default=None)),
                ('image', models.ImageField(blank=True, upload_to='pictures')),
            ],
        ),
    ]
