# Generated by Django 2.1.5 on 2019-01-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_auto_20190124_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.BooleanField(default=True)),
                ('boolean1', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trucksdata',
            name='boolean',
        ),
        migrations.AddField(
            model_name='notifications',
            name='truck_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.TrucksData'),
        ),
    ]
