# Generated by Django 2.1.5 on 2019-01-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_auto_20190124_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='boolean1',
        ),
    ]
