# Generated by Django 2.1.5 on 2019-01-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0005_auto_20190124_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='data',
            field=models.CharField(default='sds', max_length=1000),
        ),
    ]
